 pipeline {
  agent any
  environment {
    IMAGE = "omarredaa/ivolve"
    TAG = "${env.BUILD_NUMBER}"
  }
  stages {
    stage('Checkout') {
 8
      steps { checkout scm }
    }
    stage('Build Image') {
      steps {
        sh 'docker build -t $IMAGE:$TAG .'
      }
    }
    stage('Push Image') {
      steps {
        withCredentials([string(credentialsId: 'dockerhub-token', variable: 
'DOCKERTOKEN')]) {
          sh 'echo $DOCKERTOKEN | docker login -u omarredaa -
password-stdin'
          sh 'docker push $IMAGE:$TAG'
        }
      }
    }
    stage('Cleanup') {
      steps { sh 'docker image rm $IMAGE:$TAG || true' }
    }
    stage('Update Manifests & Push') {
      steps {
        sh "sed -i 's@omarredaa/ivolve:latest@$IMAGE:$TAG@g' 
kubernetes/deployment.yaml || true"
        sh 'git add kubernetes/deployment.yaml && git commit -m "update 
image" || true'
        sh 'git push origin main || true'
      }
    }
  }
 }
