 apiVersion: apps/v1
 kind: Deployment
 metadata:
  name: ivolve-web
  namespace: ivolve
 spec:
  replicas: 2
  selector:
    matchLabels:
      app: ivolve
  template:
    metadata:
      labels:
        app: ivolve
    spec:
      containers:
      - name: ivolve
        image: omarredaa/ivolve:latest
        ports:
        - containerPort: 5000
        env: [] 
